FROM python:3.10
WORKDIR /app

COPY server.py config.py requirements.txt /app/
COPY agent/ /app/agent/
COPY hls_content/ /app/hls_content/
COPY vosk-model-small-ru-0.22/ /app/vosk-model-small-ru-0.22/


RUN pip install --default-timeout=100 --no-cache-dir -r requirements.txt


EXPOSE 8000


CMD ["python", "server.py"]
